# Site settings
title: Bamboo
description: "Good Days, Good Things"
repository: "bambil/bamboo"

# Secondary Parameters
header-img: img/header.jpg
headercolor: "#FFFFFF"
logo: img/logo.png

# Tertiary Parameters
github_username: bambil
project_repository: bamboo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
