version: "3"
services:
  bamboo-connectivity:
    image: ibamboo/connectivity
    ports:
      - "1883:1883"
    environment:
			BAMBOO_BROKER_PROCESSES: 2
			BAMBOO_BROKER_PORT: 1883
	bamboo-log:
		image: ibamboo/log
		ports:
			- "8081:8081"
		environment:
			BAMBOO_DATABASE_NAME: Bamboo
			BAMBOO_DATABASE_HOST: influx
			BAMBOO_CONNECTIVITY_HOST: bamboo-connectivity
			BAMBOO_CONNECTIVITY_PORT: 1883
			BAMBOO_HTTP_HOST: 0.0.0.0
			BAMBOO_HTTP_PORT: 8081
  influx:
    image: influxdb
