version: "3"
services:
  influx:
    image: influxdb
  bamboo-connectivity:
    image: ibamboo/connectivity
    ports:
      - "1883:1883"
    environment:
      BAMBOO_BROKER_PROCESSES: 2
      BAMBOO_BROKER_PORT: 1883
  bamboo-log:
    image: ibamboo/log
    links:
      - influx
    environment:
      BAMBOO_DATABASE_NAME: Bamboo
      BAMBOO_DATABASE_HOST: influx
      BAMBOO_CONNECTIVITY_HOST: bamboo-connectivity
      BAMBOO_CONNECTIVITY_PORT: 1883
      BAMBOO_HTTP_HOST: 0.0.0.0
      BAMBOO_HTTP_PORT: 8081
  bamboo-interface:
    image: ibamboo/interface
    ports:
      - "8080:8080"
    environment:
      BAMBOO_HTTP_HOST: 0.0.0.0
      BAMBOO_HTTP_PORT: 8080
      BAMBOO_COMPONENTS_LOG: http://bamboo-log:8081
